### ISSUE TITLE
@UrlParam decorator sometimes getting 'favicon.ico' instead of string

### ISSUE THREAD

**Issue by alaborderie** [smartive/giuseppe#130]
Hi!
I am using `giuseppe@1.2.0` to handle my Cloud Functions and I ran into a bug.
One of my controllers starts like this:
```ts
@Controller('')
export class MyController {
  @Get(':aString')
  public redirect(@UrlParam('aString') aString: string): void {
    console.log(`MyController > myFunction() > aString: ${aString}`);
  }
}
```
This is hosted in Firebase Cloud Functions. Most of the times it works as expected, but it sometimes get `'favicon.ico'` as `aString`

Could not get an answer on stack, hope you will help me there or fix it if it's a bug 🙂 
Thanks!

**Comment by buehler** [comment]
Oh :-)
Do you register with a base url or just plain with no url?

I'd recommend to update to v2 😉
