### ISSUE TITLE
Expose `express.set` on giuseppe

### ISSUE THREAD

**Issue by petermanser** [smartive/giuseppe#138]
Since giuseppe is completely wrapping express it would make sense to also wrap the often used `set` method.

## Current code:

```
const app = new Giuseppe();
app.expressApp.set('view engine', 'pug');
```

## Wanted code:

```
const app = new Giuseppe();
app.set('view engine', 'pug');
```

Your thoughts?

**Comment by buehler** [comment]
Hmm.. what about a `pug-extension` ? And that pug extension / plugin could then set the view engine for you. When we coded this the first idea was to expose those express functions, but then @mfeltscher and I decided to just expose the express object so users can utilize all functions in any way they want to. So when we mix this up it would be counter-intuitive to the api designs we made so far.
