### ISSUE TITLE
Images for documentation

### ISSUE THREAD

**Issue by buehler** [smartive/giuseppe#15]
![logo](https://cloud.githubusercontent.com/assets/1067213/14689133/51624568-0746-11e6-9d93-eabc6d5f97e2.png)

**Comment by petermanser** [comment]
😍 👍

**Comment by buehler** [comment]
:D

**Comment by petermanser** [comment]
![giuseppe](https://cloud.githubusercontent.com/assets/292951/14691860/f363e562-0753-11e6-89df-aab95645084f.png)
