### ISSUE TITLE
Can we return File Response from Get Request

### ISSUE THREAD

**Issue by shubhi15** [smartive/giuseppe#178]
Hello 
Is there any way to return the file stream type response from giuseppe Get request. 
I could not find Response object coming as param within controller of GET request.

Regards
Shubhi

**Comment by buehler** [comment]
Hey. Sorry for the very late answer.

Yes, actually you can use the `reqres-plugin` and use the response by yourself. So you can return anything you want.

Plugin: https://github.com/smartive/giuseppe-reqres-plugin

**Comment by buehler** [comment]
@shubhi15 
Now you can define your own `ReturnType` and return a Buffer (for instance)
