### ISSUE TITLE
Body-Parser and Cookie-Parser packages

### ISSUE THREAD

**Issue by buehler** [smartive/giuseppe#35]
Should we add an error or a warning when `@Body()` is used and no body-parser package is installed?
A similar problem exists with the future of `@Cookie` param decorator. If there is no cookie-parser package, those two will always deliver undefined.

Maybe it's in the responsibility of the user since there could exist more than just `body-parser` or other default expressJS packages.

**Comment by buehler** [comment]
(Also it is expected behaviour when no bodyparser / cookieparser is installed)

**Comment by petermanser** [comment]
I'd add a warning if those packages are not available. This allows you to use custom body-/cookieparsers.
