### ISSUE TITLE
Route Versioning

### ISSUE THREAD

**Issue by dwirz** [smartive/giuseppe#79]
It would be nice if we could introduce some kind of versioning for same routes e.g. `@Get(':id', { version: '1.4.2' })` and `@Get(':id', { version: '2.0.0' })` via header.

**Comment by buehler** [comment]
Should it be possible `only` via header or could it be thinkable to use it with other techniques?

I'm thinking of:
- Header (customizable)
- Queryparam

Url part should not be used, since it would lead to a bad rest design (IMO)

**Comment by dwirz** [comment]
I prefer the header (customisable) variant. Because it makes an api call cleaner.

**Comment by mfeltscher** [comment]
Maybe also have a look at [node-restify](http://restify.com/#versioned-routes) - they use semver and an `Accept-Version` header.

There is also a great list about how popular sites and frameworks handle API versioning which can be found here: http://www.lexicalscope.com/blog/2012/03/12/how-are-rest-apis-versioned/
