### ISSUE TITLE
The routing does work unless you turn compiler option 'emitDecoratorMetadata' to 'true'

### ISSUE THREAD

**Issue by kfrajtak** [smartive/giuseppe#84]
Hi,
I really like your idea and the controller registration using decorators. When trying to make it work on my side I spend about an hour of debugging to find out why the routing does not work and I'm getting 402 No Content.

In `ControllerDecorator` class on line 198 you're reading the return type of the route method. However, for this to work correctly the metadata must be emitted by the `tsc` compiler and that requires compiler option `emitDecoratorMetadata` to be set to `true`. This is not emphasized in the documentation. Can you please add this note to readme document?

Thanks,
Karel

**Comment by buehler** [comment]
Hey @kfrajtak 
Thanks for the credit and many thanks for pointing this flaw out!

We will provide this information in the documentation as soon as possible. We are also planning to do a `yeoman` generator for giuseppe to bootstrap a whole application out of the box.

Cheers
Chris

**Comment by kfrajtak** [comment]
No problem!
Cheers,
Karel
