### ISSUE TITLE
Add "Fork me on GitHub" ribbon to documentation

### ISSUE THREAD

**Issue by mfeltscher** [smartive/giuseppe#93]
In order to find the repository in the documentation it would be nice to add a [For me on Github ribbon](https://github.com/blog/273-github-ribbons).

**Comment by buehler** [comment]
@mfeltscher In which color? :-)
(The headerbar will get a new color according to the correct CI)

**Comment by mfeltscher** [comment]
If the header is becoming dark blue I'd go with a white ribbon :)
